/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TrucksLazyImport = createFileRoute('/trucks')()
const DriversLazyImport = createFileRoute('/drivers')()
const CustomersLazyImport = createFileRoute('/customers')()
const AssignmentsLazyImport = createFileRoute('/assignments')()

// Create/Update Routes

const TrucksLazyRoute = TrucksLazyImport.update({
  path: '/trucks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/trucks.lazy').then((d) => d.Route))

const DriversLazyRoute = DriversLazyImport.update({
  path: '/drivers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/drivers.lazy').then((d) => d.Route))

const CustomersLazyRoute = CustomersLazyImport.update({
  path: '/customers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/customers.lazy').then((d) => d.Route))

const AssignmentsLazyRoute = AssignmentsLazyImport.update({
  path: '/assignments',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/assignments.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsLazyImport
      parentRoute: typeof rootRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersLazyImport
      parentRoute: typeof rootRoute
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversLazyImport
      parentRoute: typeof rootRoute
    }
    '/trucks': {
      id: '/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof TrucksLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AssignmentsLazyRoute,
  CustomersLazyRoute,
  DriversLazyRoute,
  TrucksLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/assignments",
        "/customers",
        "/drivers",
        "/trucks"
      ]
    },
    "/assignments": {
      "filePath": "assignments.lazy.tsx"
    },
    "/customers": {
      "filePath": "customers.lazy.tsx"
    },
    "/drivers": {
      "filePath": "drivers.lazy.tsx"
    },
    "/trucks": {
      "filePath": "trucks.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
